#!/bin/bash

if [ $# -ne 2 ]; then
	echo "Usage: $0 [infile] [outprefix]"
	exit 1
fi

if [ ! -f /usr/bin/gnuplot ]; then
	echo "Gnuplot does not appear to be installed."
	exit 1
fi

infile=$1
outprefix=$2

/usr/bin/gnuplot <<EOF

set logscale y
set term po eps color
set pointsize 1
set ylabel "Delta Time (ns) |xdd-kernel|"
set xlabel "Time in seconds"
set title "XDDCP Transfer"
set style data line

set output "${outprefix}_all.eps"
plot	'${infile}' using 1:2 title 'read_disk_start'   lw 2,\
    	'${infile}' using 1:3 title 'read_disk_end'    lw 2,\
	'${infile}' using 4:5 title 'send_net_start'    lw 2,\
	'${infile}' using 4:6 title 'send_net_end'    lw 2,\
	'${infile}' using 7:8 title 'recv_net_start'    lw 2,\
	'${infile}' using 7:9 title 'recv_net_end'    lw 2,\
	'${infile}' using 10:11 title 'write_disk_start'    lw 2,\
	'${infile}' using 10:12 title 'write_disk_end'    lw 2

set output "${outprefix}_net.eps"
plot	'${infile}' using 4:5 title 'send_net_start'   lw 2,\
	'${infile}' using 4:6 title 'send_net_end'   lw 2,\
 	'${infile}' using 7:8 title 'recv_net_start'   lw 2,\
 	'${infile}' using 7:9 title 'recv_net_end'   lw 2

set output "${outprefix}_disk.eps"
plot	'${infile}' using 1:2 title 'read_disk_start'   lw 2,\
    	'${infile}' using 1:3 title 'read_disk_end'   lw 2,\
	'${infile}' using 10:11 title 'write_disk_start'   lw 2,\
	'${infile}' using 10:12 title 'write_disk_end'   lw 2

set output "${outprefix}_src.eps"
plot	'${infile}' using 1:2 title 'read_disk_start'   lw 2,\
     	'${infile}' using 1:3 title 'read_disk_end'   lw 2,\
 	'${infile}' using 4:5 title 'send_net_start'   lw 2,\
	'${infile}' using 4:6 title 'send_net_end'   lw 2

set output "${outprefix}_dest.eps"
plot	'${infile}' using 7:8 title 'recv_net_start'   lw 2,\
    	'${infile}' using 7:9 title 'recv_net_end'   lw 2,\
	'${infile}' using 10:11 title 'write_disk_start'   lw 2,\
	'${infile}' using 10:12 title 'write_disk_end'   lw 2

EOF

