#! /bin/sh -x

############################################################################################################################
# SCENARIO 11 - RANDOM STAT() ON FILES - ONE (1) PROCESS
############################################################################################################################
# 11.01 OBJECTIVE
## To understand the file system performance of a random readdir() or stat() call with a large number of files in a large number of directories with one (1) process.
# 11.02 DESCRIPTION
## One (1) process performing a random readdir() or stat() with ten (10) million files located in ten (10) directories with one (1) million files per directory.
# Method for running the Scenario:
## 1. Create file system, mount, and tune.
## 2. Randomly make ten (10) directories. 
## 3. Randomly create in parallel one (1) million files in each of the ten (10) directories using at least one hundred (100) creation threads or processes.
## 4. Unmount file system.
## 5. Mount file system.
## 6. Start time counter.
## 7. Serial random walk using readdir() or stat() of all the files in each of the directories in a random order using only one (1) thread or process (this is the cold cache test).
## 8. Stop time counter.
## 9. Start time counter.
## 10. Serial random walk using readdir() or stat() of all the files in each of the directories in a random order using only one (1) thread or process (this is the warm cache test).
## 11. Stop time counter.
## 12. Repeat steps 4-11 at least three (3) times.
## 11.03 EXPECTED RESULTS
## No measurement is required but the performance numbers should be reported along with the test setup 
## and at least three (3) runs using cold cache and three (3) runs using warm cache. 
## The variance in reported performance should be low especially for the warm cache results.
############################################################################################################################

#PBS -q batch
#PBS -A stf006
#PBS -N S04
#PBS -j oe
#PBS -o ./results_Extreme_File_Creation.$PBS_JOBID
#PBS -l walltime=0:10:00,size=360

cd $PBS_O_WORKDIR
EXECUTABLE="./mdtest"

##############################################################################
########## Change parameters below as needed #################################
########## Note: task == process            ##################################
NODES=30                     # Number of Nodes
TPN=4                        # Tasks per Node
FPT=8                        # Files per task
ITERS=10                     # Number of times to run test
VERB="     "                 # Verbose mode "-v -v"
let "PROCS = $NODES * $TPN"  # Number of Tasks
let "PROCSbeg=          1"   # Beginning number of tasks to test
let "PROCSend= $PROCS - 1"   # Ending number of tasks to test
let "PROCStep= $PROCS / 4"   # Step number of tasks
let "PROCSby10= $PROCS / 10" # Hardwired # of directories
DATA_DIR="/lustre/widow1/scratch/${USER}/mdtests/testfiles" # Test file directory ...must exist
LAUNCH_CMD="aprun -n $PROCS -N $TPN"
PRE_CREATE=false             # If true, create 0-length files as specified below accross OSTs
############# Should not have to change stuff below this line #################

############################################################################################
# create 0 length files,  stripe 1, round robin files across MAX_OSTs OSTs. tune to suit.
############################################################################################
if [ "$PRE_CREATE" ]
then
DATA_FILE="mdtest"
date
iost=0
iproc=0
while [ "$iproc" -lt "$PROCS" ]
do
ifile=0
while [ "$ifile" -lt "$FPT" ]
do
lfs setstripe -s 1m -c 1 -i $iost ${DATA_DIR}/${DATA_FILE}.${iproc}.${ifile}
iost=`expr $iost + 1`
ifile=`expr $ifile + 1`
done
iproc=`expr $iproc + 1`
done
fi

date
##########################################################################################################
## 2. Randomly make ten (10) directories. 
##         How are directories made randomly??? Humor the spec writers...
## 3. Randomly create in parallel one (1) million files in each of the ten (10) directories 
##    using at least one hundred (100) creation threads or processes.
##         OK, Let's create a bunch with random sizes, and then random stat 'em. And we do it with 
##         ten (10) parallel launches of mdtest. This ought to confuse any meta data server!!!
##########################################################################################################
for dir in "09 01 04 03 02 06 05 07 08 00"
do
rm -fr ${dir}
mkdir  ${dir}
# File create, random sizes between 1-64KB, concurrent random stat tests, files only, $FPT files per task/process
aprun -n $PROCS -N $TPN $EXECUTABLE -d ${dir} -n $FPT -i 1  -F -w 1024 -W 65536  -k -f $PROCSby10 -l $PROCSby10  $VERB &
done
wait
# build ordered list
rm -f  files_ls.out
touch files_ls.out
for dir in "09 01 04 03 02 06 05 07 08 00"
do
ls -1 ${dir}/* >> files_ls.out
done
# Randomly shuffle ordered list
Shufflem < files_ls.out
##########################################################################################################
## 6. Start time counter.
## 7. Serial random walk using readdir() or stat() of all the files in each of the directories in a random order 
##    using only one (1) thread or process (this is the cold cache test).
##      We would have to keep track of everything file read to make sure ALL files got stat()'ed. But then
##      it would not really be random if done that way. But we could make a random list and stat in that order!
##      As with the creates, launch ten(10) instances of mdtest, one for each directory
## 8. Stop time counter.
##########################################################################################################
date
lfs getstripe ${DATA_DIR}/*
# File meta data tests, files,  directories, no task offset
#aprun -n $PROCS -N $TPN $EXECUTABLE  -d $TEST_DIR_LOC -n $FPT -i $ITERS       -N 0  -f $PROCSbeg -l  $PROCSend  -s $PROCStep  $VERB

# File meta data tests, files,  directories, random task offset
#aprun -n $PROCS -N $TPN $EXECUTABLE  -d $TEST_DIR_LOC -n $FPT -i $ITERS       -R 0   -f $PROCSbeg -l  $PROCSend  -s $PROCStep  $VERB

echo "Finished File Meta tests"
